### ISSUE TITLE
Links to Adobe DAM content seem to have domain overridden 

### ISSUE THREAD

**Issue by sforschen** [hlxsites/elixirsolutions#118]
Links to Adobe DAM content seem to be overridden 

https://main--elixirsolutions--hlxsites.hlx.live/providers

My current assumption is this will resolve when we go live as it seems to be auto-replacing the domain. 

https://www.elixirsolutions.com/content/dam/elixirdotcom/providers/Q2-Communication_061923.pdf
https://main--elixirsolutions--hlxsites.hlx.live/content/dam/elixirdotcom/providers/Q2-Communication_061923.pdf

**Comment by shsteimer** [comment]
yea, we relativize links so once we go live it will be resolved, but we can change the logic slightly so that it ignores certain paths or something along those lines.

**Comment by sforschen** [comment]
Ok cool that works for me. I don't anticipate any problems currently just wanted to make sure it is expected.
