### ISSUE TITLE
Columns thirds remove a.button styling and let it default to styles defined padding

### ISSUE THREAD

**Issue by sforschen** [hlxsites/elixirsolutions#123]
columns.css : 31

let's remove all button customization for the columns thirds

.columns.thirds a.button {
    /* font-size: var(--body-font-size-m); */
    /* padding: 5px 25px; */
}

**Comment by janefrommaine** [comment]
@sforschen, can you share which page has a button styled link in a thirds column?
Would it be better to remove the .button class?

**Comment by sforschen** [comment]
@janefrommaine 
 
 button works well in these spots

https://main--elixirsolutions--hlxsites.hlx.live/aboutus

bottom where it says careers.

https://main--elixirsolutions--hlxsites.hlx.page/plansponsors/pharmacy-benefit-management

blue section
