### ISSUE TITLE
Table breaking mobile view in blog and two-column pages

### ISSUE THREAD

**Issue by janefrommaine** [hlxsites/elixirsolutions#137]
Layout is broken in mobile when tables have content that needs to scroll horizontally.

Example:
https://main--elixirsolutions--hlxsites.hlx.live/blog/unmasking-the-medications-you-shouldnt-be-paying-for

Screenshot:
<img width="275" alt="elx-mobile-table-blog-layout-error" src="https://github.com/hlxsites/elixirsolutions/assets/12315337/68f4124b-3ca8-4e97-89ab-dd904cd3fa25">

**Comment by sforschen** [comment]
Looks like its not just the table but all the content is cut off

**Comment by sforschen** [comment]
I am trying to rebuild the table, maybe it's something in the paste that is holding on to some formatting.

**Comment by sforschen** [comment]
Nope it's not the table itself it's all tables in blogs and I presume anything with columns on mobile.

@janefrommaine I am not sure what the best route is, we could set the table wrapper at a specific size on mobile so it can also scroll left to right, set a different overflow so it scrolls horizontally, or maybe some sort of scaling the whole thing down but can zoom in on click.

**Comment by sforschen** [comment]
https://medium.com/allenhwkim/mobile-friendly-table-b0cb066dbc0e

This is a much more complicated but also correct way to display the info on mobile.

**Comment by janefrommaine** [comment]
@sforschen, I like that idea of stacking the table content in mobile. I want to research if there are any accessibility drawbacks to this approach. We actually use it in some places in the member portal but have seemed to move away from it. I'll add that as a separate ticket in our backlog for research.

For launch, I have a fix to add the scrollbar back to the table in mobile. I'm thinking this is good enough for now so the page doesn't look broken. 
https://github.com/hlxsites/elixirsolutions/pull/142
