### ISSUE TITLE
darker Highlight section Links need to be white

### ISSUE THREAD

**Issue by sforschen** [hlxsites/elixirsolutions#144]
This is rarely used but when the highlight is dark the links need to be light:

![image](https://github.com/hlxsites/elixirsolutions/assets/134433004/55c6e79e-3b29-41f4-8193-7305525d61bf)

**Comment by sforschen** [comment]
I think the cards need a link setting for dark backgrounds.

**Comment by sforschen** [comment]
https://main--elixirsolutions--hlxsites.hlx.live/aboutus/our-services

Thats the page it was on, changed the highlight to the secondary one in the meantime.

**Comment by janefrommaine** [comment]
@sforschen, for the card-more-cta arrow, should this inherit the same color as the link?
Blue for the normal section
White when the section is the darker variant

![image](https://github.com/hlxsites/elixirsolutions/assets/12315337/21a26b3d-d5c7-4272-8b24-2ae575bb50f7)

**Comment by sforschen** [comment]
@janefrommaine yeah there is really no reason for it to be any different from the link color. So yes let it inherit away.
