### ISSUE TITLE
Remove custom h1 size from blog posts

### ISSUE THREAD

**Issue by sforschen** [hlxsites/elixirsolutions#147]
Blog H1 can match the rest of the site, let's just remove the custom size

styles line 433

.blog main .default-content-wrapper h1 {
    font-size: var(--heading-font-size-l);
}

**Comment by janefrommaine** [comment]
@sforschen, do you think we should also remove the other custom heading sizes in the blog posts?

 .blog main .default-content-wrapper h1 { font-size: var(--heading-font-size-l) }
.blog main .default-content-wrapper h2 { font-size: var(--heading-font-size-l) }
.blog main .default-content-wrapper h3 { font-size: var(--heading-font-size-m) }
.blog main .default-content-wrapper h4 { font-size: var(--heading-font-size-m) }
.blog main .default-content-wrapper h5 { font-size: var(--heading-font-size-xs) }
.blog main .default-content-wrapper h6 { font-size: var(--heading-font-size-xs) }

**Comment by sforschen** [comment]
@janefrommaine nah, one of those sets the subscribe text on the sidebar and in the blog feed on the home page to fit properly. For now just the h1. I do want to address those but with the columns and sidebar highlight bigger task we may be able to remove that customization at the text at the same time.
