### ISSUE TITLE
Blog SEO Optimization

### ISSUE THREAD

**Issue by sforschen** [hlxsites/elixirsolutions#195]
Elixir Solutions SEO Optimization 

Blog 

EEAT (Expertise, Experience, Authority, Trustworthiness) Optimization 

Adding author bio 

Include an author byline for every blog article written 

A close up of a label
![image](https://github.com/hlxsites/elixirsolutions/assets/134433004/270c5361-af19-4520-b413-7405d77d9339)

Proves to Google that the article was written by someone with credentials. This is especially important for sites that write on health or finance related topics 

Author bio pages for every author on the site (EX: https://www.healthline.com/authors/sarah-garone)  
![image](https://github.com/hlxsites/elixirsolutions/assets/134433004/9cc5d43b-ca34-420c-ad20-dabfafbf47b2)

Adding a “reviewed by” byline 

Under the author byline, include a “reviewed by” byline 

Proves to Google that this information has been vetted by multiple trustworthy sources 

Content freshness 

Include a “date published” byline 

Especially when the content information may change often, it’s important to give insight into when the article was published and if it’s been updated to reflect any new data or information 

A close up of a label

Optimize headers 

Title Tag 

Shorten some title tags that are over Google’s character limit 
![image](https://github.com/hlxsites/elixirsolutions/assets/134433004/7bd604b9-a721-4e7e-8e03-db9c6b5cd17b)

You want to avoid long title tags that will get cut off on the results page 

Include higher search volume terms in headers and title tag 

For the [NASH article](https://blog.elixirsolutions.com/nash-the-growing-and-costly-disease-you-probably-dont-know-about-but-should), a better title tag would be: “Nonalcoholic steatohepatitis (NASH): Symptoms, Treatment, and More” 

Using a keyword tool like Google Keyword Planner, you can compile a list of long-tail queries with search 

![image](https://github.com/hlxsites/elixirsolutions/assets/134433004/3b6bb641-5e6d-4950-8c7d-e2596a68e66d)

Structure articles so that the header tags make it easy for users to navigate to different sections. Keyword research is a great way to create header tags. 

For the NASH article, these would be good sample H2s: 

What is Nonalcoholic steatohepatitis (NASH)? 

NASH Causes 

NASH Symptoms 

NASH Treatment 

Conversion 

Optimizing landing pages 

Optimize headers and title tags 

Making title tags longer or including more keywords that pertain to the page 

EX: https://www.elixirsolutions.com/members/specialty-rx 

The current title tag is “Specialty Rx” 

This title tag could be optimized by including other keywords that are pertinent to the page (EX: Specialty Rx: Specialty Pharmacy Support & Care) 

“Specialty Rx” should be added to the H1 tag as well 

Including CTAs 

Add more CTAs on core landing pages in order to improve the user journey and get more customers in the funnel 

EX: https://www.elixirsolutions.com/members/specialty-rx 

This page could have more CTAs or internal links to other pages on the site that encourage membership or allow users to sign up 

https://www.cvsspecialty.com/ is an example of a page that does this well	  

Add more internal links 

All pages on the site could do with more internal links. Internal links not only help Google discover and value more pages, but they also allow users to better navigate across the site 

We shouldn’t hide tons of internal links in accordions when we can use CTA or in-text links to add internal linking 

EX: https://www.elixirsolutions.com/members/specialty-rx 

The majority of the internal links on this page are hidden under accordions

**Comment by sforschen** [comment]
@janefrommaine these were recommendations from Rite Aid and I do like the idea of updating the blogs to include them. I know this might not fit all in this sprint but we can expand it over a couple.

**Comment by sforschen** [comment]
@janefrommaine @seanmilfort In the Elixir universal Figma file I have added to the example blog post what I would like the addition of author, date, and clinical reviewer to look like. I will be creating Bio pages for our writers and reviewers. 

![image](https://github.com/hlxsites/elixirsolutions/assets/134433004/31817176-0cda-4022-90c6-2325dd188737)

In the blog metadata, we already include the date, we will need to build the author and reviewer. the author and reviewer will need to be able to link to a bio page.  The section will need to hide parts if no data is present.

The icon is in the Figma file and I have the SVG I can upload to the repo to pull in
 ![Review](https://github.com/hlxsites/elixirsolutions/assets/134433004/051ea97e-9e67-41e3-a683-86d558336f0b)

A lot of the other changes are suggestions for authoring.

**Comment by sforschen** [comment]
@janefrommaine Does not exist yet as we only have a handful of these in use. I do think we should set up a naming convention before I start putting them into the repo. Right now I just name them as a description of what they are no other thought into it yet. I will set up a call for us.

**Comment by janefrommaine** [comment]
@sforschen a couple questions about the Author and Reviewed Clinician...

1. Will they always have a bio page?
2. Will the urls to the bio pages always be internal, or will we need to support external urls?
3. What is the url pattern for the location of these bios?

On the authoring side, I was thinking to add two new rows to the page's Metadata table
1. Author
2. Reviewer

I noticed that if I make the value for these two new rows hyperlinks, Franklin strips out the hyperlink by the time I can use it in the javascript.
I was wondering if we will always have the same url pattern for the location of the author and reviewer bios. If so, we don't need to add the hyperlinks in the word doc, I can just hardcode those urls via the javascript.
What do you think?

![image](https://github.com/hlxsites/elixirsolutions/assets/12315337/267aff2c-929b-421a-8b8a-981556f5b3e4)

**Comment by sforschen** [comment]
@janefrommaine 

1. No they will not always have a bio page sometimes it will just be text and no link
There is also a possibility there will be more than one author or reviewer separated by commas
We need to take into account an auther may have credentials after their name

2. URLs for the foreseeable future will be internal. I could see us having guests eventually but not in the near future and maybe we can handle those with redirects or something like the bin routing

3. https://www.elixirsolutions.com/aboutus/bios/firstname-lastname
or in the case of team bios like clinical or compliance team follows the same first last
https://www.elixirsolutions.com/aboutus/bios/clinical-team
We may want to handle this with the same method we do bin routing, a spreadsheet with the names and what page they link to

**Comment by sforschen** [comment]
@janefrommaine Yes thats the insane credentialing I am thinking of I do like the idea of storing it in the spreadsheet maybe the instructions for blog authoring include using the spreadsheet to get the name so it's always correct. 

If we do that we should be able to also query the metadata and have a posts by  author section down the road similar to our posts by topic that we have now.

I think it would be exceedingly rare we have two people with the same first and last name if it does happen we had the spreadsheet we could have a unique identifier (007) rather than by name then the URL is just whatever we select and add to the spreadsheet

**Comment by sforschen** [comment]
Reopening to fix author and publish date showing on bottom of blog page
