### ISSUE TITLE
Add default URL direction on register and login - group lookup

### ISSUE THREAD

**Issue by sforschen** [hlxsites/elixirsolutions#202]
We may need to set up a default if no matching group is found on the group lookup section. If they get me a list I can fix it the correct way but if not we can have the group lookup take them to the edx portal if no match is found

registration-form.js

For context:

The website was updated this morning however the lookup did not change and these group #s do not exist on the old site mapping.

It looks like the old lookup defaults to https://member.elixirsolutions.com/ which is not good because that was likely directing people to the wrong portal periodically and causing calls as well. I can add a default back in but it’s not a solution as anything that doesn’t match a group lookup, including typos, automatically gets sent to the EDx portal. This actually explains why we get so many contact us form submissions about not being able to login as this has never been set up correctly. This also doesn’t work for mail pharmacy users who may have a  bin and group number that is not ours as they have a different plan/insurance providers.    

As for the recon question, I have been trying to resolve it for months now. If I had a definitive list of bins, groups, and their associated portals I could audit the site coding to make sure we have all the correct mapping. This should be done regularly and should be part of implementation, however, I have not found a source for that information.

If I had a list I could fix the sites lookup correctly and fairly quickly.

**Comment by janefrommaine** [comment]
@sforschen, I wonder how the the contact us form submissions and help phone calls are resolved. 
Does the help line have a way to look this information up somehow?

I noticed that my card's Group No is not in the groups tab of the lookup spreadsheet.
