### ISSUE TITLE
Add salesforce ID to form data selection in word document

### ISSUE THREAD

**Issue by sforschen** [hlxsites/elixirsolutions#209]
![image](https://github.com/hlxsites/elixirsolutions/assets/134433004/d2b6e4f3-07ff-4668-842b-a7d9c5dfffac)
adding a SF ID to this selection so the user can swap them out

**Comment by sforschen** [comment]
https://riteaidonline.sharepoint.com/:w:/r/sites/AEM/_layouts/15/Doc.aspx?sourcedoc=%7BCD83B1A5-60D5-4AC2-9D48-2DE3C1C9B174%7D&file=employers.docx&action=default&mobileredirect=true

https://www.elixirsolutions.com/plansponsors/pharmacy-benefit-management/employers

**Comment by sforschen** [comment]
@janefrommaine the lead went through and has the SF ID appended.

**Comment by janefrommaine** [comment]
Woohoo! Closing this ticket.
