### ISSUE TITLE
CDN redirects for special characters

### ISSUE THREAD

**Issue by shsteimer** [hlxsites/elixirsolutions#66]
legacy urls like https://www.elixirsolutions.com/register&login can't be redirected at franklin due to & in the path. need to redirect these at the CDN:

- /register&login
- /register&login/envisionrx-members
- /register&login/group_lookup
- /register&login/new-plan-lookup

**Comment by sforschen** [comment]
Completed in the launch then unlaunch, will double check this next launch.
