### ISSUE TITLE
Accessibility - Screen Reader

### ISSUE THREAD

**Issue by sforschen** [hlxsites/elixirsolutions#77]
NVDA SR - When page first loads, each page announces "<Page name> document busy blank" and it doesn't say anything after the page has loaded so it is difficult to know when the page is ready. (This doesn't happen every time but happens most times)

**Comment by shsteimer** [comment]
Think I'm going to need som guidance on this one. I don't think we've run across this before, and my google-fu is failing me in finding how we can solve.
