### ISSUE TITLE
Accessibility - General Notations

### ISSUE THREAD

**Issue by sforschen** [hlxsites/elixirsolutions#86]
Many of these we can fix on our end post-launch but I wanted to post the general summary of the accessibility comments. 

1.	Search field and all other forms/input fields need labels
2.	Skipped heading levels 
3.	Review alt text - most should probably be empty
a.	All stock photos should be empty
b.	Remove "envelope" icons from contact us page
4.	Add a skip to content link
5.	Let users know links open in new tab (put in link text)
6.	Buttons go to other sites which will potentially cause issues
a.	"View our open positions" button goes to ultipro - felt disorienting
7.	Redundant link text - "Click here for Elixir…"
8.	Consider replacing all caps with sentence case (ex. Navigation reads "U.S." Instead of "us")
9.	Clickable images with header, description then link are coded as lists -- is there another way to do this -- seems confusing using list item and whole card as link
10.	"Trusted by thousands..." Learn more links have redundant alt (repeating "learn more")
a.	Make sure links with identical text have descriptive hidden text (ex. Learn more..about Pharmacy Benefit Management)

**Comment by shsteimer** [comment]
some of this is authoring, some not. lets talk through them.

And to be clear, we are more than happy to assist with the authoring changes, just need to decide what we are doin and who is doing it.
